// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbURL =
  process.env['DATABASE_URL'] ??
  `postgresql://${process.env['PGUSER']}:${process.env['PGPASSWORD']}
@${process.env['PGHOST']}:${process.env['PGPORT']}
/${process.env['PGDATABASE']}?schema=public`;

console.log("Database URL:", dbURL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --env-file=.env ./src/animals/entities/db-seed.ts"
  },
  datasource: {
    // url: process.env["DATABASE_URL"],
    url: dbURL,
  },
});
